name: network_manage
description: A Dart package for managing blockchain network configurations
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0

